add stow-quick.sh and improve scripts in bin
Former-commit-id: 9e6cb44c824b2952c30e14823c570cb56430f1a8
Former-commit-id: 0796ab9039e537368bdac375a0c08fbfccbc4cc6
Former-commit-id: dc4a46c27243605cf2bc2ae53a9af3b676caaed2
Former-commit-id: e272398df681f369d95393125d883c92d0c9eb48
Former-commit-id: d2028db6e7aed46e8602ff29c63308123d7b6142 [formerly ea81fdfa8e0019eee44ef6287e1aa64dbe8a43df]
Former-commit-id: 226d574a74850429fb47a4dedfd3fdede83f84e1

diff --git a/bin/.bin/t-gentoo-chroot b/bin/.bin/t-gentoo-chroot
--- a/bin/.bin/t-gentoo-chroot
+++ b/bin/.bin/t-gentoo-chroot
@@ -4,12 +4,12 @@
 #
 
 if [[ "x$1" == "x" ]]; then
-	echo "USAGE: $0 /mnt/gentoo"
+	echo "usage: $0 /path/to/chroot" >&2
 	exit 1
 fi
 
-if [[ ! -d "$1"  ]]; then
-	echo "The specified path doesn't exist: $1"
+if [[ ! -d "$1" ]]; then
+	echo "error: the specified path doesn't exist: $1" >&2
 	exit 1
 fi
 
@@ -20,3 +20,5 @@ sudo mount -o bind /proc "$1/proc"
 sudo mount --rbind /dev  "$1/dev"
 sudo mount --rbind /sys  "$1/sys"
 sudo chroot "$1/" /bin/env -i TERM=$TERM /bin/bash
+
+set +x
diff --git a/bin/.bin/t-world b/bin/.bin/t-world
--- a/bin/.bin/t-world
+++ b/bin/.bin/t-world
@@ -9,7 +9,7 @@ function ctrl_c	(){
 	exit 1
 }
 
-# Ask for password upfront.
+# Ask for sudo password upfront.
 sudo -v
 
 # One pseudo package manager to rule them all.
@@ -26,7 +26,7 @@ if [[ "$(uname)" == "Darwin" ]]; then
 	# macOS: homebrew
 	if command -v brew &>/dev/null; then
 		brew update
-		brew upgrade --all
+		brew upgrade
 		brew cleanup
 		brew prune
 		brew doctor
@@ -70,5 +70,5 @@ if [[ -e /etc/debian_version ]] && command -v apt &>/dev/null; then
 	exit
 fi
 
-echo "ERROR: your system / package manager could not be identified."
+echo "error: your system and/or package manager could not be identified." >&2
 exit 1
